name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Set env variable
        run: echo "NG_APP_BUTTER_TOKEN=${{ secrets.NG_APP_BUTTER_TOKEN }}" >> $GITHUB_ENV

      - name: Generate environment.ts
        run: npx ts-node scripts/set-env.ts

      - name: Build Angular app
        run: npm run build
